"""init schema

Revision ID: 8972f42ba57e
Revises: 
Create Date: 2025-12-28 19:47:42.271498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8972f42ba57e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('word_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_locations_location_id'), 'word_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_word_locations_word_id'), 'word_locations', ['word_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.Column('text_normalized', sa.String(length=140), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_text_normalized'), 'words', ['text_normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_text_normalized'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_word_locations_word_id'), table_name='word_locations')
    op.drop_index(op.f('ix_word_locations_location_id'), table_name='word_locations')
    op.drop_table('word_locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
